deploy:
    name: CD - Deploy to Kubernetes
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f namespace.yaml
        kubectl apply -f configmap.yml
        kubectl apply -f mongodb-deployment.yaml
        kubectl apply -f app-deployment.yaml
        kubectl apply -f gateway.yaml
        kubectl apply -f httproute.yaml
``